const mockIssues = [
    {
        id: 1,
        issueKey: "BL-101",
        title: "Login fails after password reset",
        description:
            "Users cannot log in after resetting their password.",
        status: "IN PROGRESS",
        severity: "CRITICAL",
        priority: "HIGH",
        assignee: "Rahul",
        component: "Authentication",
        release: "v2.4",
    },
    {
        id: 2,
        issueKey: "BL-102",
        title: "Dashboard loading slowly",
        description:
            "Dashboard requests take several seconds to complete.",
        status: "OPEN",
        severity: "HIGH",
        priority: "MEDIUM",
        assignee: "Priya",
        component: "Dashboard",
        release: "v2.4",
    },
    {
        id: 3,
        issueKey: "BL-103",
        title: "Incorrect component health score",
        description:
            "Component health calculation displays incorrect values.",
        status: "IN REVIEW",
        severity: "MEDIUM",
        priority: "HIGH",
        assignee: "Unassigned",
        component: "Intelligence",
        release: "v2.5",
    },
    {
        id: 4,
        issueKey: "BL-104",
        title: "Dependency graph does not update",
        description:
            "Graph visualization does not refresh after dependency changes.",
        status: "RESOLVED",
        severity: "LOW",
        priority: "LOW",
        assignee: "Arjun",
        component: "Dependency Engine",
        release: "v2.4",
    },
    {
        id: 5,
        issueKey: "BL-105",
        title: "Email notification not sent",
        description:
            "Users do not receive issue assignment notifications.",
        status: "OPEN",
        severity: "HIGH",
        priority: "HIGH",
        assignee: "Rahul",
        component: "Notifications",
        release: "v2.5",
    },
    {
        id: 6,
        issueKey: "BL-106",
        title: "Search returns stale results",
        description:
            "Issue search sometimes displays outdated results.",
        status: "IN PROGRESS",
        severity: "MEDIUM",
        priority: "MEDIUM",
        assignee: "Priya",
        component: "Search",
        release: "v2.5",
    },
    {
        id: 7,
        issueKey: "BL-107",
        title: "Project settings fail to save",
        description:
            "Project settings are not persisted correctly.",
        status: "OPEN",
        severity: "CRITICAL",
        priority: "HIGH",
        assignee: "Arjun",
        component: "Projects",
        release: "v2.5",
    },
    {
        id: 8,
        issueKey: "BL-108",
        title: "Comment editor loses content",
        description:
            "Unsaved comment content disappears unexpectedly.",
        status: "IN REVIEW",
        severity: "MEDIUM",
        priority: "LOW",
        assignee: "Priya",
        component: "Comments",
        release: "v2.5",
    },
    {
        id: 9,
        issueKey: "BL-109",
        title: "Release risk calculation is incorrect",
        description:
            "Release risk does not account for critical dependencies.",
        status: "IN PROGRESS",
        severity: "CRITICAL",
        priority: "HIGH",
        assignee: "Rahul",
        component: "Intelligence",
        release: "v2.5",
    },
    {
        id: 10,
        issueKey: "BL-110",
        title: "Activity timeline missing events",
        description:
            "Some issue status changes are missing from the activity timeline.",
        status: "OPEN",
        severity: "LOW",
        priority: "LOW",
        assignee: "Unassigned",
        component: "Activity",
        release: "v2.5",
    },
    {
        id: 11,
        issueKey: "BL-111",
        title: "Issue assignment dropdown broken",
        description:
            "Assignment changes are not reflected immediately.",
        status: "OPEN",
        severity: "HIGH",
        priority: "MEDIUM",
        assignee: "Arjun",
        component: "Issues",
        release: "v2.5",
    },
    {
        id: 12,
        issueKey: "BL-112",
        title: "Workflow transition rejected incorrectly",
        description:
            "Valid transitions are sometimes rejected by the UI.",
        status: "IN PROGRESS",
        severity: "HIGH",
        priority: "HIGH",
        assignee: "Rahul",
        component: "Workflow",
        release: "v2.5",
    },
];

export default mockIssues;